language: ruby
bundler_args: --path $HOME/.bundle --with test
cache:
  directories:
    - $HOME/.bundle

script:
 - bundle exec jekyll build --baseurl /proc-linux-cz --destination _site/proc-linux-cz
 - bundle exec htmlproofer ./_site --disable-external --empty-alt-ignore
# - linkchecker --ignore-url=^mailto https://proc.linux.cz/

deploy:
- provider: pages
  skip-cleanup: true
  local-dir: _site/proc-linux-cz
  github-token: $GITHUB_TOKEN
  on:
    branch: master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
