language: ruby

install:
 - bundle install
 - gem install html-proofer -v '~> 3.8'

script:
 - bundle exec jekyll build --baseurl /proc-linux-cz --destination _site/proc-linux-cz
 - cd _site
 - htmlproofer . --disable-external --empty-alt-ignore
 - cd -

deploy:
- provider: pages
  skip-cleanup: true
  local-dir: _site/proc-linux-cz
  github-token: $GITHUB_TOKEN
  on:
    branch: master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build

cache: bundler
