language: ruby
bundler_args: --path $HOME/.bundle --with test
cache:
  directories:
    - $HOME/.bundle

script:
 - bundle exec jekyll build --baseurl /proc-linux-cz --destination _site/gh-pages/proc-linux-cz
 - bundle exec htmlproofer _site/gh-pages --disable-external --empty-alt-ignore
# - linkchecker --ignore-url=^mailto https://proc.linux.cz/

before_deploy:
 - bundle exec jekyll build --destination _site/production
 - LAST_GIT_TAG="$(git describe --abbrev=0 --tags)"
 - tar -cvzf "$LAST_GIT_TAG.tar.gz" -C _site/production/ .

deploy:
- provider: pages
  skip-cleanup: true
  local-dir: _site/gh-pages/proc-linux-cz
  github-token: $GITHUB_TOKEN
  on:
    branch: master
- provider: releases
  skip_cleanup: true
  file: "$LAST_GIT_TAG.tar.gz"
  api_key: $GITHUB_TOKEN
  on:
    branch: master
    tags: true

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
